# Generated by Django 5.1.4 on 2025-01-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Característica')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='PricingPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor')),
                ('has_feature', models.BooleanField(default=False, verbose_name='Disponível')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.planfeature', verbose_name='Característica')),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pricingplan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Característica do Plano',
                'verbose_name_plural': 'Características dos Planos',
            },
        ),
    ]
